name: QA

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    container: python:3.8.10
    
    steps:
    - uses: actions/checkout@v4

    - name: Check types
      run: make check-types
    
    - name: Run tests
      run: make test
